trigger:
- master

variables:
  tag: '$(Build.BuildId)'
  
pool:
  name: Hosted Ubuntu 1604
  timeoutInMinutes: 20
  
steps:
- task: Docker@0
  displayName: 'Build an image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: DockerHub
    imageName: 'bsvnhll/pradeep-demo:$(tag)'

- task: Docker@0
  displayName: 'Push an image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: DockerHub
    action: 'Push an image'
    imageName: 'bsvnhll/pradeep-demo:$(tag)'
