trigger:
- master

variables:
  tag: '$(Build.BuildId)'
  
pool:
  name: Hosted Ubuntu 1604
  timeoutInMinutes: 20
  
steps:
- script: | 
    docker build -t bsvnhll/pradeep-demo:$(tag) .
- script: |
    docker push bsvnhll/pradeep-demo:$(tag)
